// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARKE04L8HNHQE1EdmECNS8qpTsr7StEAk',
    appId: '1:235604589364:web:98eaed189f69186ae60361',
    messagingSenderId: '235604589364',
    projectId: 'qride-ccb57',
    authDomain: 'qride-ccb57.firebaseapp.com',
    storageBucket: 'qride-ccb57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0SYhLJP_Gdmjv6YU_6WSvAF9JKa8XTG8',
    appId: '1:235604589364:android:3a292818a9138d30e60361',
    messagingSenderId: '235604589364',
    projectId: 'qride-ccb57',
    storageBucket: 'qride-ccb57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6uP6qkkrUICSxBqeRazHIRfYt3-yqf54',
    appId: '1:235604589364:ios:75233b73e1ed2a14e60361',
    messagingSenderId: '235604589364',
    projectId: 'qride-ccb57',
    storageBucket: 'qride-ccb57.appspot.com',
    iosBundleId: 'com.example.qrideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6uP6qkkrUICSxBqeRazHIRfYt3-yqf54',
    appId: '1:235604589364:ios:0b62c24fcc8b7509e60361',
    messagingSenderId: '235604589364',
    projectId: 'qride-ccb57',
    storageBucket: 'qride-ccb57.appspot.com',
    iosBundleId: 'com.example.qrideApp.RunnerTests',
  );
}
